#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    actor_id:
      required: true
      type: number
      example: 1
    first_name:
      required: true
      type: string
      example: "lakkyreddy"
    last_name:
      required: true
      type: string
      example: "vamsi"
    last_update:
      required: true
      type: datetime
      example: "2015-12-17T00:00:00Z"